# add the module dependencies here
# USEMODULE += random

USEMODULE += gcoap
USEMODULE += cord_ep_standalone
USEMODULE += uri_parser

USEMODULE += credman
USEMODULE += credman_load
USEMODULE += prng_sha1prng
USEMODULE += sock_dtls
USEMODULE += gcoap_dtls
USEPKG += tinycbor
USEPKG += tinydtls

